### ISSUE TITLE
error of running Linear.java from Eclipse

### ISSUE THREAD

**Issue by usact** [scipopt/JSCIPOpt#22] opened 2020-03-13 05:10 UTC
My question is relevant to my previous one. 
https://github.com/SCIP-Interfaces/JSCIPOpt/issues/21
But, it is different, I created a new post.

I have downloaded and installed SCIP and JSCIP and built them successfully. 

I am trying to run the example from https://github.com/SCIP-Interfaces/JSCIPOpt/blob/master/examples/Linear.java

from Eclipse.

But, I got error:

      public class Linear
     {
          public static void main(String args[])
          {
              // load generated C-library
              System.loadLibrary("jscip"); // error here 
         
error:

        Exception in thread "main" java.lang.UnsatisfiedLinkError: no jscip in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at Linear.main(Linear.java:9)

I have done many search for a solution here and also on stackoverflow but none of them work. 

My OS :

 MacOS Mojave  (10.14.6)

My java:

     openjdk version "1.8.0_222" 
     OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_222-b10)
     OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.222-b10, mixed mode)

      javac -version
      javac 1.8.0_222

I downloaded SCIP from
 
     https://scip.zib.de/download.php?fname=scipoptsuite-6.0.2.tgz
  
 After building JSCIP, I have only the three files in 

      $ ls build/Release/
      examples.jar	libjscip.dylib	scip.jar

       
I have added the path as lib in Eclipse so that java can find it.  But, it does not work. 

What is "jscip" lib really needed ? Is this "libjscip.dylib	" ? 

Also, I have added the /buil folder to Eclipse by following 

     https://javarevisited.blogspot.com/2013/04/what-is-javalibrarypath-how-to-set-in-Eclipse.html
 
But, I still got an error:

       # A fatal error has been detected by the Java Runtime Environment:

      #  SIGSEGV (0xb) at pc=0x0000000128bcd319, pid=49502, tid=0x0000000000001903

     # JRE version: OpenJDK Runtime Environment (8.0_222-b10) (build 1.8.0_222-b10)
      # Java VM: OpenJDK 64-Bit Server VM (25.222-b10 mixed mode bsd-amd64 compressed oops)
     # Problematic frame:
     # C  [libawt_lwawt.dylib+0x48319]  JNI_OnLoad+0x91

thanks

**Comment by kkofler** [comment] 2024-10-16 02:24
Duplicate of #10.

**Closed by kkofler** 2024-10-16 02:24 UTC
