### ISSUE TITLE
I don't get errors on Windows, but I get errors in Docker. Why

### ISSUE THREAD

**Issue by ph1633128102** [scipopt/JSCIPOpt#49] opened 2024-09-13 04:02 UTC
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f7c765d690f, pid=1, tid=0x00007f7cb84c6700
#
# JRE version: OpenJDK Runtime Environment (8.0_412-b08) (build 1.8.0_412-b08)
# Java VM: OpenJDK 64-Bit Server VM (25.412-b08 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libscip.so.9.1+0x61790f]  SCIPisPackingPartitioningOrbitope+0x16f
#
# Core dump written. Default location: //core or core.1
#
# If you would like to submit a bug report, please visit:
#   https://access.redhat.com/support/cases/
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
```

**Comment by kkofler** [comment] 2024-09-13 08:35
Without more details on what you are trying to do:
* What distribution are you on? The bug report link sounds like RHEL, is that it? Which version?
* Are you using the latest JSCIP from git master? (You should.) Or if not, which revision?
* Which version of SCIP are you using? (If you used a different version at compile time than at runtime, then please mention both versions. That should technically work, but there may be bugs limiting the binary compatibility. So recompiling against the version used at runtime would be the first thing I would try in that case.)
* Can you share a minimal testcase that reproduces the crash for you? I am **not** asking for your whole application, especially not if it is proprietary, but for a test case that is as small as possible and still reproduces the crash. (In particular, the test case should be **compilable** so I can try to reproduce the crash with it.)

I cannot really help you, so please provide the missing information. (I am using JSCIP on GNU/Linux and it does not crash for me. And I doubt the Docker container makes any difference there.)

**Comment by kkofler** [comment] 2024-09-26 09:48
Can you please provide the missing information? Otherwise, I will have to close this report as non-reproducible.

**Comment by kkofler** [comment] 2024-10-16 02:13
I cannot reproduce this bug. Insufficient details were provided.

**Closed by kkofler** 2024-10-16 02:13 UTC
